### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by iperov** [S12P/Inpainting#3]
Your repo does not work.

**Comment by iperov** [comment]
lmao check your code, stupid noob

**Comment by S12P** [comment]
Install OpenCV and Numpy. and try this python3 inpainting.py tests/Tigre/tigre.jpg tests/Tigre/masque_tigre.jpg 
its works

I Check

**Comment by S12P** [comment]
you insult others but at least say why it doesn't work. Whereas for two years nobody has said anything because it works very well.

**Comment by S12P** [comment]
I thought that a great specialist like you seem could at least say there is a problem for this reason instead of arriving as a chef is saying "nothing works"
